sonar.projectName=Ved_goal_manager
sonar.host.url=http://localhost:9000
sonar.token=sqp_9575dd35d462f62fea7125126550d01b028f9106
sonar.projectKey=Ved_goal_manager
# Demo token section (replace with your actual token for private projects)
# sonar.login=<YOUR_SONAR_TOKEN_HERE>
# sonar.organization=<YOUR_ORGANIZATION_KEY>
# sonar.projectKey=Ved_goal_manager

