sonar.projectName=Ved_goal_manager
sonar.host.url=http://localhost:9000
sonar.token=sqp_645b6ab6acc95731b4105b38287af29bad7d4392
sonar.projectKey=Ved_goal_manager
# Demo token section (replace with your actual token for private projects)
# sonar.login=<YOUR_SONAR_TOKEN_HERE>
# sonar.organization=<YOUR_ORGANIZATION_KEY>
# sonar.projectKey=Ved_goal_manager

